### PR TITLE
[FX-NULL] Pass parameter to build-push-release-image

### PR DESCRIPTION
**Pull request by sashuk**
### Description

The `build-push-release-image` has to pass the `registry-name` parameter.

Please see https://toptal-core.slack.com/archives/C03VBF0J6/p1731003271609519?thread_ts=1730905440.129699&cid=C03VBF0J6 for more details.

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

### CODE REVIEW

**Comment by sashuk** [comment]
@toptal-anvil ping reviewers

**Comment by sashuk** [comment]
@toptal-anvil ping reviewers

**Review by p0deje — APPROVED** [review]

**Comment by p0deje** [comment]
- [ ] Please don't merge until we have PR in HireGlobal updating to a new version

**Comment by sashuk** [comment]
@p0deje The https://github.com/toptal/hire-global/pull/396 is ready, will merge it right after the release if changes from this pull request

**Pull request merged**
