### PR TITLE
[FX-4380] Fix Storybook temploy link truncation

### PR DESCRIPTION
**Pull request by mkrl**
[FX-4520](https://toptal-core.atlassian.net/browse/FX-4520)

### Description

Hostnames are actually truncated to 45 characters, not 63, acttording to our helm chart helpers.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

[FX-4520]: https://toptal-core.atlassian.net/browse/FX-4520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by TomasSlama — APPROVED** [review]

**Comment by sashuk** [comment]
@mkrl Can you please provide guidelines on how to test it? Is it enough to run the temploy like in https://github.com/toptal/staff-portal/pull/11489#issuecomment-1816142681 and remove the postfix?

> We need to check for other products like client-portal though.

Will this be done as part of this ticket?

**Comment by mkrl** [comment]
@sashuk I'm checking with client and talent portal right now. I am not 100% confident it's safe to merge just yet. I think it might not be possible to test in staff-portal since this is an action that can be triggered only when it's on master.

**Comment by sashuk** [comment]
@mkrl Got it, thanks!

**Review by sashuk — APPROVED** [review]
Looks good (assuming that tests in other portal will still be conducted)! @mkrl maybe we could test it with couple of force-merges in Staff Portal, I think it should be totally fine

**Pull request merged**
