### PR TITLE
Use global npm registry

### PR DESCRIPTION
**Pull request by Jakub-Kwak**
### Description

Describe the changes and motivations for the pull request, unless evident from the title.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

### CODE REVIEW

**Comment by sashuk** [comment]
Hello, @Jakub-Kwak! Can you please specify if the pull request is ready for review? If not, can it be moved to draft for now?

**Comment by Jakub-Kwak** [comment]
@sashuk I've checked and this fix is still used only in [screening-wizard-frontend](https://github.com/search?q=org%3Atoptal%20ci-fix-yarn-install&type=code). Let me ask the owner of the repo if they can switch back to master. If they confirm, I'll close this PR since it was only a temporary fix.

**Comment by Jakub-Kwak** [comment]
[PR](https://github.com/toptal/screening-wizard-frontend/pull/1403) created ☝️

**Comment by Jakub-Kwak** [comment]
[No workflow uses](https://github.com/search?q=org%3Atoptal%20ci-fix-yarn-install&type=code) `ci-fix-yarn-install` branch anymore.

**Pull request closed without merging**
