### PR TITLE
chore: bump gh action versions

### PR DESCRIPTION
**Pull request by LashaJini**
### Description

Describe the changes and motivations for the pull request, unless evident from the title.

### Development checks

- Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

### CODE REVIEW

**Review by LashaJini — COMMENTED** [review]
I don't think changeset needed in this case.

**Review by OndrejTuma — COMMENTED** [review]
Looks good 👌 
But I think the changeset is needed. 
Unless its okay that users will keep using actions without this change until some other release comes along 🙂

**Review by separatio — APPROVED** [review]
Looks good. Definitely add changeset. :+1:

**Comment by LashaJini** [comment]
@toptal-anvil ping reviewers

**Review by OndrejTuma — APPROVED** [review]
Looks good 🎉

**Review by dmaklygin — APPROVED** [review]

**Pull request merged**
